import {
  createCipheriv,
  createDecipheriv,
  createHash,
  createHmac,
  timingSafeEqual,
  randomBytes,
} from "crypto";
import type { Request } from "express";
import { logger } from "./logger";

const ALGORITHM = "aes-256-gcm";
const IV_LEN = 12;
const TAG_LEN = 16;
const STATE_TTL_MS = 10 * 60 * 1000;

function deriveKey(secret: string): Buffer {
  return createHash("sha256").update(secret).digest();
}

function encryptToken(token: string, secret: string): string {
  const key = deriveKey(secret);
  const iv = randomBytes(IV_LEN);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const encrypted = Buffer.concat([cipher.update(token, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, tag, encrypted]).toString("base64url");
}

function decryptToken(encoded: string, secret: string): string | null {
  try {
    const key = deriveKey(secret);
    const buf = Buffer.from(encoded, "base64url");
    if (buf.length < IV_LEN + TAG_LEN + 1) return null;
    const iv = buf.subarray(0, IV_LEN);
    const tag = buf.subarray(IV_LEN, IV_LEN + TAG_LEN);
    const ciphertext = buf.subarray(IV_LEN + TAG_LEN);
    const decipher = createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
  } catch {
    return null;
  }
}

function getSecret(): string {
  return process.env.SESSION_SECRET ?? "dev-secret-change-in-prod";
}

export function setGithubToken(req: Request, token: string): void {
  if (!req.session) {
    logger.warn({ requestId: req.id }, "Attempted to set GitHub token without an active session object");
    return;
  }
  const encrypted = encryptToken(token, getSecret());
  req.session.githubToken = encrypted;
  logger.info(
    { requestId: req.id, encryptedLength: encrypted.length },
    "Stored encrypted GitHub token in session",
  );
}

export function getGithubToken(req: Request): string | null {
  const raw = req.session?.githubToken as string | undefined | null;
  if (!raw) {
    logger.debug({ requestId: req.id }, "No GitHub token found in session");
    return null;
  }
  const token = decryptToken(raw, getSecret());
  if (!token) {
    logger.warn(
      { requestId: req.id, encryptedLength: raw.length },
      "Failed to decrypt GitHub token from session",
    );
    return null;
  }
  return token;
}

export function clearGithubToken(req: Request): void {
  if (req.session) {
    req.session.githubToken = null;
    logger.info({ requestId: req.id }, "Cleared GitHub token from session");
    return;
  }
  logger.warn({ requestId: req.id }, "Attempted to clear GitHub token without an active session object");
}

export function destroySession(req: Request): void {
  req.session = null;
  logger.info({ requestId: req.id }, "Destroyed session");
}

/**
 * Generate a self-contained HMAC-signed CSRF state token.
 * No server-side storage needed — the signature is verified in the callback.
 * Format (base64url): <nonce>:<timestamp>:<hmac-sha256>
 */
export function generateOauthState(): string {
  const secret = getSecret();
  const nonce = randomBytes(16).toString("hex");
  const timestamp = Date.now().toString();
  const message = `${nonce}:${timestamp}`;
  const sig = createHmac("sha256", secret).update(message).digest("hex");
  return Buffer.from(`${message}:${sig}`).toString("base64url");
}

/**
 * Verify a CSRF state token generated by generateOauthState().
 * Returns true if the signature is valid and the token is within TTL.
 */
export function verifyOauthState(state: string): boolean {
  try {
    const secret = getSecret();
    const decoded = Buffer.from(state, "base64url").toString("utf8");
    const parts = decoded.split(":");
    if (parts.length !== 3) return false;
    const [nonce, timestamp, providedSig] = parts;
    const message = `${nonce}:${timestamp}`;
    const expectedSig = createHmac("sha256", secret).update(message).digest("hex");
    const sigsMatch = timingSafeEqual(
      Buffer.from(expectedSig, "hex"),
      Buffer.from(providedSig, "hex"),
    );
    const isRecent = Date.now() - parseInt(timestamp, 10) < STATE_TTL_MS;
    return sigsMatch && isRecent;
  } catch {
    return false;
  }
}

export function getCallbackUrl(req: Request): string {
  const override = process.env.GITHUB_CALLBACK_URL;
  if (override) return override;

  const proto =
    (req.headers["x-forwarded-proto"] as string | undefined)?.split(",")[0].trim() ??
    req.protocol ??
    "https";
  const host =
    (req.headers["x-forwarded-host"] as string | undefined)?.split(",")[0].trim() ??
    (req.headers["host"] as string | undefined) ??
    process.env.REPLIT_DEV_DOMAIN ??
    "localhost";
  return `${proto}://${host}/api/github/auth/callback`;
}
